"""
Data models for the generation stage.
"""
from dataclasses import dataclass, field
from typing import List, Optional, Dict
from datetime import datetime


@dataclass
class EvidenceRef:
    """A reference to a source chunk used in a draft section."""
    chunk_id: str
    source_label: str    # e.g. "contract_2024.pdf (p.3)"
    excerpt: str         # relevant snippet from the chunk
    relevance_score: float


@dataclass
class DraftSection:
    """A single section of a generated draft memo."""
    section_id: str
    title: str
    content: str
    evidence_refs: List[EvidenceRef] = field(default_factory=list)
    is_supported: bool = True   # False if no evidence backs this section

    @property
    def citation_labels(self) -> List[str]:
        return [e.source_label for e in self.evidence_refs]


@dataclass
class DraftMemo:
    """
    Full generated draft memo — the primary output of the generation stage.
    """
    memo_id: str
    doc_id: str
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    to_field: str = "Supervising Attorney"
    from_field: str = "LegalMind AI (Draft)"
    re_field: str = ""
    sections: List[DraftSection] = field(default_factory=list)
    total_evidence_chunks: int = 0
    model_used: str = ""
    generation_warnings: List[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Render the memo as formatted Markdown with inline citations."""
        lines = [
            "# MEMORANDUM",
            "",
            f"**TO:** {self.to_field}",
            f"**FROM:** {self.from_field}",
            f"**RE:** {self.re_field}",
            f"**DATE:** {self.generated_at[:10]}",
            f"**GENERATED BY:** {self.model_used}",
            "",
            "---",
            "",
        ]
        for section in self.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            if section.evidence_refs:
                labels = "; ".join(
                    f"[{e.source_label}]" for e in section.evidence_refs
                )
                lines.append(f"\n*Sources: {labels}*")
            if not section.is_supported:
                lines.append("\n> ⚠️ *No direct evidence found for this section.*")
            lines.append("")

        if self.generation_warnings:
            lines.append("---")
            lines.append("## System Warnings")
            for w in self.generation_warnings:
                lines.append(f"- ⚠️ {w}")

        lines.append("---")
        lines.append("## Supporting Evidence Index")
        seen = set()
        for section in self.sections:
            for ev in section.evidence_refs:
                if ev.chunk_id not in seen:
                    seen.add(ev.chunk_id)
                    lines.append(f"\n**[{ev.source_label}]** (score: {ev.relevance_score:.2f})")
                    lines.append(f"> {ev.excerpt[:200]}...")

        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "memo_id": self.memo_id,
            "doc_id": self.doc_id,
            "generated_at": self.generated_at,
            "to": self.to_field,
            "from": self.from_field,
            "re": self.re_field,
            "total_evidence_chunks": self.total_evidence_chunks,
            "sections": [
                {
                    "id": s.section_id,
                    "title": s.title,
                    "content": s.content,
                    "evidence_refs": [
                        {
                            "chunk_id": e.chunk_id,
                            "source": e.source_label,
                            "score": e.relevance_score,
                            "excerpt": e.excerpt[:150],
                        }
                        for e in s.evidence_refs
                    ],
                    "is_supported": s.is_supported,
                }
                for s in self.sections
            ],
            "model_used": self.model_used,
            "warnings": self.generation_warnings,
        }
